###THE FUNCTION READS IN A TEXT FILE AND CREATES A NEW TEXT FILE CALLED "BinOutput.txt" THAT CONTAINS THE BINARY CODES FOR THE GIVEN FILE.###
# TASK 4 By: Jiayuan Zhang (MICHAEL)#
def txt_to_bin (file_name
#TAKE A STRING AS INPUT TO THE FUNCTION

#OPEN THE FILE & READ IN THE VALUES

#CLOSE THE FILE

#FUNCTION FIND ALL THE BINARY CODES FOR THE GIVEN TEXT FILE

#DETERMINE THE NUMBER OF BITS NEEDED TO STORE THE TEXT FILE

#WRITE THE BINARY VALUES TO A FILE NAMED "BinOutput.txt" 
